/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Vote } from "./Vote";
export * as factories from "./factories";
export { Vote__factory } from "./factories/Vote__factory";
